Repository AY2223S1-CS2103T-F12-4/tp, pull requests merged in 2022-10, with the labels that each got.

#57 Refactor/update models
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/student/NextOfKin.java
  src/main/java/seedu/address/model/person/student/UniqueStudentList.java
  src/main/java/seedu/address/model/person/student/exceptions/DuplicateStudentException.java
  src/main/java/seedu/address/model/person/student/exceptions/StudentNotFoundException.java
  src/main/java/seedu/address/model/person/tutor/UniqueTutorList.java
  src/main/java/seedu/address/model/person/tutor/exceptions/DuplicateTutorException.java
  src/main/java/seedu/address/model/person/tutor/exceptions/TutorNotFoundException.java
  src/main/java/seedu/address/model/tuitionclass/Subject.java
  src/main/java/seedu/address/model/tuitionclass/Time.java
  src/main/java/seedu/address/model/tuitionclass/TuitionClass.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonAdaptedTuitionClass.java
  src/main/java/seedu/address/storage/JsonAdaptedTutor.java
  src/test/data/JsonSerializableAddressBookTest/typicalTuitionClassesAddressBook.json
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/student/UniqueStudentListTest.java
  src/test/java/seedu/address/model/person/tutor/UniqueTutorListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTuitionClassTest.java
  src/test/java/seedu/address/testutil/TuitionClassBuilder.java
  src/test/java/seedu/address/testutil/TypicalTuitionClasses.java
Labels: type.Task, priority.High

#62 Edit DeleteCommand
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: type.Story, priority.High

#67 Add 3 second pause after exit command input
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Enhancement, priority.Low

#84 Refactor/add nok class
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/nextofkin/NextOfKin.java
  src/main/java/seedu/address/model/person/nextofkin/Relationship.java
  src/main/java/seedu/address/model/person/student/NextOfKin.java
  src/main/java/seedu/address/model/person/student/Student.java
  src/main/java/seedu/address/model/tuitionclass/Day.java
  src/main/java/seedu/address/model/tuitionclass/Subject.java
  src/main/java/seedu/address/storage/JsonAdaptedNextOfKin.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/nextofkin/NextOfKinTest.java
  src/test/java/seedu/address/model/person/nextofkin/RelationshipTest.java
  src/test/java/seedu/address/model/person/student/NextOfKinTest.java
  src/test/java/seedu/address/model/person/student/StudentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/storage/JsonSerializableStudentAddressBookTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/NextOfKinBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalAddressBook.java
  src/test/java/seedu/address/testutil/TypicalNextOfKins.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
  src/test/java/seedu/address/testutil/TypicalTutors.java
Labels: type.Task, priority.Medium

#85 Add sort command
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/student/Student.java
  src/main/java/seedu/address/model/person/student/UniqueStudentList.java
  src/main/java/seedu/address/model/person/tutor/Tutor.java
  src/main/java/seedu/address/model/person/tutor/UniqueTutorList.java
  src/main/java/seedu/address/model/tuitionclass/TuitionClass.java
  src/main/java/seedu/address/model/tuitionclass/UniqueTuitionClassList.java
  src/main/java/seedu/address/storage/JsonSerializableStudentAddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableTuitionClassAddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableTutorAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: type.Story, priority.Medium

#100 Update DeveloperGuide.md on sort command implementation
  docs/DeveloperGuide.md
Labels: type.Task

#116 New export feature
  build.gradle
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/ExportStudentCsv.java
  src/main/java/seedu/address/storage/ExportTuitionClassCsv.java
  src/main/java/seedu/address/storage/ExportTutorCsv.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Story, priority.Medium

#124 Fix bug where an invalid entity json causes all json files to be reset
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/data/JsonAddressBookStorageTest/emptyStudentAddressBook.json
  src/test/data/JsonAddressBookStorageTest/emptyTuitionClassAddressBook.json
  src/test/data/JsonAddressBookStorageTest/emptyTutorAddressBook.json
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
Labels: type.Bug, priority.High, severity.Low

#132 Update UserGuide with export feature
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#135 Fix bug where themes css files aren't found
  src/main/java/seedu/address/commons/core/GuiSettings.java
Labels: type.Bug

#118 Feat/find-by-fields
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/StudentContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/TuitionClassContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/TutorContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/tuitionclass/Time.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Story, priority.Medium

#131 Fix bug for assign and unassign command
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/UnassignCommandParser.java
Labels: type.Bug

#146 Update user guide
  docs/UserGuide.md
  docs/images/Ui_annotated.png
  docs/images/description_difference.png
  docs/images/list_tabs.png
  docs/images/titile_big_logo.png
Labels: priority.Medium

#147 Update UserGuide
  docs/UserGuide.md
  docs/images/exportButton.png
Labels: type.Task, priority.High
