Repository AY2223S1-CS2103T-F12-4/tp, pull requests merged in 2022-11, with the labels that each got.

#209 Fix bug where tags and classes for a student will appear under nok cells
  src/main/java/seedu/address/storage/ExportStudentCsv.java
Labels: type.Bug, severity.Low

#208 Fix Ui bugs
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, priority.Low

#211 Fix bug where list is not sorted properly from old to new in some cases
  src/main/java/seedu/address/model/person/student/Student.java
  src/main/java/seedu/address/model/person/student/UniqueStudentList.java
  src/main/java/seedu/address/model/person/tutor/Tutor.java
  src/main/java/seedu/address/model/person/tutor/UniqueTutorList.java
  src/main/java/seedu/address/model/tuitionclass/TuitionClass.java
  src/main/java/seedu/address/model/tuitionclass/UniqueTuitionClassList.java
  src/main/java/seedu/address/storage/JsonSerializableStudentAddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableTuitionClassAddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableTutorAddressBook.java
  src/test/java/seedu/address/model/person/student/UniqueStudentListTest.java
  src/test/java/seedu/address/model/person/tutor/UniqueTutorListTest.java
  src/test/java/seedu/address/model/tuitionclass/UniqueTuitionClassListTest.java
Labels: type.Bug, severity.Low

#212 Fix/find command tag fail
  docs/UserGuide.md
  src/main/java/seedu/address/model/StudentContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/TuitionClassContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/TutorContainsKeywordsPredicate.java
Labels: type.Bug, severity.High

#214 Fix bug where invocation error occurs after editing an entity
  src/main/java/seedu/address/model/AddressBook.java
Labels: type.Bug, priority.High, severity.High

#216 Refactor code for creating student.csv
  src/main/java/seedu/address/storage/ExportStudentCsv.java
Labels: type.Task

#220 Fix bug when adding 2 exact same entries except for their names
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/student/UniqueStudentList.java
  src/main/java/seedu/address/model/person/tutor/UniqueTutorList.java
  src/main/java/seedu/address/model/tuitionclass/UniqueTuitionClassList.java
Labels: type.Bug, severity.Medium

#226 Update myStudent description and fix export section link
  docs/UserGuide.md
Labels: type.Task

#235 Update user guide to use more active voice and fix grammatical and sentence structure mistakes
  docs/UserGuide.md
Labels: type.Task

#234 Fix Ui bugs
  docs/images/personDescription.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
Labels: priority.High

#229 Add testing for find
  src/test/java/seedu/address/model/StudentContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/TuitionClassContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/TutorContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/tuitionclass/TimeTest.java
Labels: type.Task, priority.Low

#231 Add diagrams for find
  docs/DeveloperGuide.md
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindActivityDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/team/tantzeyeong.md
Labels: type.Task, priority.Low

#245 Update sort portion of developer guide
  docs/DeveloperGuide.md
  docs/diagrams/SortSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/SortSequenceDiagram.png
  docs/images/StorageClassDiagram.png
Labels: type.Task

#249 Update sort portion of developer guide
  docs/DeveloperGuide.md
Labels: type.Task

#255 Fix formatting error for code block in table
  docs/DeveloperGuide.md
Labels: type.Task

#256 Add warning about modifying .json files directly
  docs/UserGuide.md
Labels: type.Task

#257 Update initialization and exit messages from Address Book to myStudent
  src/main/java/seedu/address/MainApp.java
Labels: type.Task

#266 Update nopehax PPP
  docs/team/nopehax.md
Labels: type.Task

#270 Fix table formatting in sort portion of developer guide
  docs/DeveloperGuide.md
Labels: type.Task

#271 Change nopehax responsibility to storage
  docs/AboutUs.md
Labels: type.Task
